<?php

/**
 * @file
 * Hook implementations for the Symfony Mailer BC test module.
 */

/**
 * Implements hook_mail().
 */
function symfony_mailer_bc_test_mail($key, &$message, $params) {
  if ($key == 'bc_test') {
    $message['subject'] = 'Backwards compatible mail sent via hook_mail().';
    $message['body'][] = 'This email is sent via hook_mail().';
    $message['body'][] = symfony_mailer_bc_test_add_template_to_body();
    $message['headers']['Cc'] = 'cc@example.com';
  }
}

/**
 * Adds a rendered (Twig) template file to the body of the test email message.
 *
 * This mimics the logic implemented in Drupal Commerce, when sending the
 * "commerce order receipt" mail.
 */
function symfony_mailer_bc_test_add_template_to_body() {
  /** @var \Drupal\Core\Theme\ThemeManagerInterface $theme_manager */
  $theme_manager = \Drupal::service('theme.manager');
  /** @var \Drupal\Core\Render\RendererInterface $renderer */
  $renderer = \Drupal::service('renderer');
  $current_theme = $theme_manager->getActiveTheme()->getName();
  $template = [
    '#theme' => 'bc_test_mail',
    '#current_theme' => $current_theme,
  ];
  return $renderer->render($template);
}

/**
 * Implements hook_theme().
 */
function symfony_mailer_bc_test_theme() {
  return [
    'bc_test_mail' => [
      'variables' => ['current_theme' => NULL],
    ],
  ];
}
