/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

(function (Backbone, Drupal) {
  Drupal.addToCart.AddToCartModel = Backbone.Model.extend({
    defaults: {
      defaultVariation: '',
      selectedVariation: '',
      attributeOptions: {},
      injectedFields: {},
      variations: {},
      variationCount: 0,
      type: 'commerce_product_variation_attributes',
      quantity: 0
    },
    initialize: function initialize() {
      this.set('variationCount', Object.keys(this.get('variations')).length);
      this.set('selectedVariation', this.getVariation(this.get('defaultVariation')));
    },
    getDefaultVariation: function getDefaultVariation() {
      return this.get('defaultVariation');
    },
    getAttributes: function getAttributes() {
      return this.get('attributeOptions')[this.getSelectedVariation().uuid].attributes;
    },
    getVariations: function getVariations() {
      return this.get('variations');
    },
    getVariation: function getVariation(uuid) {
      return this.attributes['variations'][uuid];
    },
    getResolvedVariation: function getResolvedVariation(selectedAttributes) {
      var _this = this;

      function getSelectedAttributeValueId(fieldName) {
        if (typeof selectedAttributes[fieldName] === 'object') {
          return selectedAttributes[fieldName].attribute_value_id.toString();
        }
        return selectedAttributes[fieldName].toString();
      }
      function getVariationAttributeValueId(fieldName, variation) {
        if (!variation.hasOwnProperty(fieldName)) {
          return '';
        }
        if (typeof variation[fieldName] === 'object') {
          return variation[fieldName].attribute_value_id.toString();
        }
        return variation[fieldName].toString();
      }

      var attributes = [].concat(_toConsumableArray(this.getAttributes()));
      var variations = Object.keys(this.getVariations()).map(function (key) {
        return _this.getVariation(key);
      });
      var selectedVariation = null;

      while (attributes.length > 0) {
        for (var variation in variations) {
          var match = true;
          for (var attribute in attributes) {
            var fieldName = 'attribute_' + attributes[attribute].id;
            if (getVariationAttributeValueId(fieldName, variations[variation]) !== getSelectedAttributeValueId(fieldName)) {
              match = false;
            }
          }
          if (match) {
            selectedVariation = variations[variation];
            break;
          }
        }
        if (selectedVariation !== null) {
          break;
        }

        attributes.pop();
      }
      return selectedVariation;
    },
    getSelectedVariation: function getSelectedVariation() {
      return this.attributes['selectedVariation'];
    },
    setSelectedVariation: function setSelectedVariation(uuid) {
      this.set('selectedVariation', this.getVariation(uuid));
    },
    getVariationCount: function getVariationCount() {
      return this.get('variationCount');
    },
    getRenderedAttribute: function getRenderedAttribute(fieldName) {
      return this.get('attributeOptions')[this.getSelectedVariation().uuid].renderedAttributes[fieldName];
    },
    getInjectedFieldsForVariation: function getInjectedFieldsForVariation(uuid) {
      return this.attributes['injectedFields'][uuid];
    },
    getType: function getType() {
      return this.attributes['type'];
    },
    setQuantity: function setQuantity(quantity) {
      this.set('quantity', quantity);
    },
    getQuantity: function getQuantity() {
      return this.attributes['quantity'];
    }
  });
})(Backbone, Drupal);